-- Ativação de Row Level Security (RLS) para todas as tabelas do sistema
-- Isso bloqueia acessos via Supabase REST API (frontend client) usando anon key,
-- e continua permitindo normalmente os acessos do Drizzle via Server Actions (Service Role).

ALTER TABLE "pessoa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pessoa_classificacao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "anexo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "endereco" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dados_aluno" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dados_funcionario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "nivel_ensino" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "serie" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "disciplina" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "grade_curricular" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funcionario_habilitacao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ano_letivo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sala" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "turma" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quadro_horario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "turma_docente" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "matricula" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ocorrencia_aluno" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "historico_escolar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "periodo_avaliativo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "avaliacao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "nota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "diario_classe" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "frequencia_aluno" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contrato_escolar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "documento_gerado" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_prontuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_prontuario_evolucao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_pei" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_pei_meta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_atendimento" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aee_documento" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vinculo_responsavel_aluno" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mural_aviso" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "aviso_ciente" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notas_boletim" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calendario_pedagogico" ENABLE ROW LEVEL SECURITY;
